# ЗПАД | Лабораторна робота № 2
### Тема: Наука про дані: підготовчий етап
**Частина:** 2
---
**Виконала:** Городиська Анна ФБ-44

### 1: Імпорт бібліотек.
Спочатку підключаємо все необхідне.

In [2]:
import pandas as pd
import numpy as np
import timeit

### 2: Очищення та зчитування даних. 
Тут ми зчитаємо дані. Проаналізувавши цей файл можна зрозуміти, що в ньому роздільником є крапка з комою, а пропущені значення позначені знаком питання. Для зручності я одразу це врахувала.

In [3]:
print("Зчитуємо дані... Це може зайняти кілька секунд.")
df = pd.read_csv('data/household_power_consumption.txt', sep=';', na_values=['?'], low_memory=False)

# Частина з чисткою, видаляємо рядки з пропущеними даними
df = df.dropna()

# Перетворюємо Date та Time у зручний формат datetime для подальшої фільтрації
# Формат дати в файлі: dd/mm/yyyy
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%d/%m/%Y %H:%M:%S')

print("Очищення завершено! Розмір датасету:", df.shape)
display(df.head())

Зчитуємо дані... Це може зайняти кілька секунд.
Очищення завершено! Розмір датасету: (2049280, 10)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,2006-12-16 17:24:00
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00

### 3: Вибірки та профілювання часу (timeit)

3.1: Обрати всі записи, у яких загальна активна споживана потужність перевищує 5 кВт.

In [4]:
def task1_high_power(dataframe):
    start_time = timeit.default_timer()
    

    result = dataframe[dataframe['Global_active_power'] > 5.0]
    
    execution_time = timeit.default_timer() - start_time
    print(f"Завдання 3.1 виконано за {execution_time:.5f} секунд. Знайдено записів: {len(result)}")
    
    return result


res1 = task1_high_power(df)


print("\n--- Записи, де загальна активна потужність > 5 кВт ---")
display(res1)

Завдання 3.1 виконано за 0.00696 секунд. Знайдено записів: 17547

--- Записи, де загальна активна потужність > 5 кВт ---

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0,2006-12-16 17:35:00
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0,2006-12-16 17:36:00
...,...,...,...,...,...,...,...,...,...,...
2069356,22/11/2010,18:40:00,5.408,0.150,231.50,23.6,48.0,0.0,0.0,2010-11-22 18:40:00
2069357,22/11/2010,18:41:00,5.528,0.144,232.48,24.6,53.0,0.0,0.0,2010-11-22 18:41:00
2071586,24/11/2010,07:50:00,5.172,0.050,235.18,22.0,0.0,38.0,17.0,2010-11-24 07:50:00
2071587,24/11/2010,07:51:00,5.750,0.000,234.40,24.6,0.0,39.0,17.0,2010-11-24 07:51:00
2072997,25/11/2010,07:21:00,5.074,0.240,238.55,21.4,1.0,2.0,18.0,2010-11-25 07:21:00

3.2: Обрати всі записи, у яких сила струму лежить в межах 19-20 А, для них виявити ті, у яких пральна машина та холодильних споживають більше, ніж бойлер та кондиціонер.

In [5]:
def task2_current_and_appliances(dataframe):
    start_time = timeit.default_timer()
    result = dataframe[
        (dataframe['Global_intensity'] >= 19.0) & 
        (dataframe['Global_intensity'] <= 20.0) & 
        (dataframe['Sub_metering_2'] > dataframe['Sub_metering_3'])
    ]
    execution_time = timeit.default_timer() - start_time
    print(f"Завдання 2 виконано за {execution_time:.5f} секунд. Знайдено {len(result)} записів.")
    return result
print("--- Результат ---")
res2 = task2_current_and_appliances(df)
display(res2)

--- Результат ---
Завдання 2 виконано за 0.02230 секунд. Знайдено 2509 записів.

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
45,16/12/2006,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0,2006-12-16 18:09:00
460,17/12/2006,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0,2006-12-17 01:04:00
464,17/12/2006,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0,2006-12-17 01:08:00
475,17/12/2006,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0,2006-12-17 01:19:00
476,17/12/2006,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0,2006-12-17 01:20:00
...,...,...,...,...,...,...,...,...,...,...
2071589,24/11/2010,07:53:00,4.666,0.000,235.72,19.8,0.0,39.0,17.0,2010-11-24 07:53:00
2071590,24/11/2010,07:54:00,4.694,0.000,236.78,19.8,0.0,39.0,18.0,2010-11-24 07:54:00
2071591,24/11/2010,07:55:00,4.602,0.000,237.08,19.4,0.0,40.0,17.0,2010-11-24 07:55:00
2071592,24/11/2010,07:56:00,4.536,0.000,237.03,19.0,0.0,39.0,17.0,2010-11-24 07:56:00
2071593,24/11/2010,07:57:00,4.626,0.000,236.78,19.4,0.0,39.0,17.0,2010-11-24 07:57:00

3.3: Обрати випадковим чином 500000 записів (без повторів елементів вибірки), для них обчислити середні величини усіх 3-х груп споживання електричної енергії

In [6]:
def task3_random_sample_means(dataframe):
    start_time = timeit.default_timer()
    # sample(n=..., replace=False) гарантує відсутність повторів
    sample_df = dataframe.sample(n=500000, replace=False)
    means = sample_df[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()
    execution_time = timeit.default_timer() - start_time
    print(f"Завдання 3 виконано за {execution_time:.5f} секунд.")
    print("Середні значення груп споживання:\n", means)
    return means
    
print("--- Результат ---")
res3 = task3_random_sample_means(df)
display(res1)

--- Результат ---
Завдання 3 виконано за 0.27441 секунд.
Середні значення груп споживання:
 Sub_metering_1    1.121090
Sub_metering_2    1.293126
Sub_metering_3    6.465874
dtype: float64

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0,2006-12-16 17:35:00
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0,2006-12-16 17:36:00
...,...,...,...,...,...,...,...,...,...,...
2069356,22/11/2010,18:40:00,5.408,0.150,231.50,23.6,48.0,0.0,0.0,2010-11-22 18:40:00
2069357,22/11/2010,18:41:00,5.528,0.144,232.48,24.6,53.0,0.0,0.0,2010-11-22 18:41:00
2071586,24/11/2010,07:50:00,5.172,0.050,235.18,22.0,0.0,38.0,17.0,2010-11-24 07:50:00
2071587,24/11/2010,07:51:00,5.750,0.000,234.40,24.6,0.0,39.0,17.0,2010-11-24 07:51:00
2072997,25/11/2010,07:21:00,5.074,0.240,238.55,21.4,1.0,2.0,18.0,2010-11-25 07:21:00

3.4: Обрати ті записи, які після 18-00 споживають понад 6 кВт за хвилину в середньому, серед відібраних визначити ті, у яких основне споживання електроенергії у вказаний проміжок часу припадає на пральну машину, сушарку, холодильник та освітлення (група 2 є найбільшою), а потім обрати кожен третій результат із першої половини та кожен четвертий результат із другої половини.

In [7]:
def task4_complex_filter(dataframe):
    start_time = timeit.default_timer()
    
    # Спочатку фільтруємо за умовами
    filtered_df = dataframe[
        (dataframe['Datetime'].dt.hour >= 18) & 
        (dataframe['Global_active_power'] > 6.0) & 
        (dataframe['Sub_metering_2'] > dataframe['Sub_metering_1']) & 
        (dataframe['Sub_metering_2'] > dataframe['Sub_metering_3'])
    ]
    
    # Ділимо на дві половини
    half_index = len(filtered_df) // 2
    first_half = filtered_df.iloc[:half_index]
    second_half = filtered_df.iloc[half_index:]
    
    # Обираємо кожен 3 та 4 елемент відповідно
    res_first = first_half.iloc[::3]
    res_second = second_half.iloc[::4]
    
    # Об'єднуємо результати
    final_result = pd.concat([res_first, res_second])
    
    execution_time = timeit.default_timer() - start_time
    print(f"Завдання 4 виконано за {execution_time:.5f} секунд. Знайдено {len(final_result)} записів.")
    return final_result

    
print("--- Результат ---")
res4 = task4_complex_filter(df)
display(res4)

--- Результат ---
Завдання 4 виконано за 0.13505 секунд. Знайдено 310 записів.

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0,2006-12-16 18:05:00
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0,2006-12-16 18:08:00
17494,28/12/2006,20:58:00,6.386,0.374,236.63,27.0,1.0,36.0,17.0,2006-12-28 20:58:00
17498,28/12/2006,21:02:00,8.088,0.262,235.50,34.4,1.0,72.0,17.0,2006-12-28 21:02:00
17501,28/12/2006,21:05:00,7.230,0.152,235.22,30.6,1.0,73.0,17.0,2006-12-28 21:05:00
...,...,...,...,...,...,...,...,...,...,...
2066466,20/11/2010,18:30:00,6.620,0.314,229.00,29.2,18.0,34.0,16.0,2010-11-20 18:30:00
2066470,20/11/2010,18:34:00,6.266,0.360,229.82,27.6,14.0,35.0,16.0,2010-11-20 18:34:00
2066474,20/11/2010,18:38:00,6.302,0.376,229.65,27.8,15.0,34.0,17.0,2010-11-20 18:38:00
2066478,20/11/2010,18:42:00,6.238,0.344,229.37,27.6,14.0,35.0,16.0,2010-11-20 18:42:00
2066482,20/11/2010,18:46:00,6.438,0.308,229.26,28.4,13.0,39.0,16.0,2010-11-20 18:46:00

### 4: Нормування та стандартизація:

Завдання: Пронормувати та стандартизувати вибраний датасет.

In [8]:
# Обираємо лише числові колонки для нормування та стандартизації
numeric_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage', 
                'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']

print("--- Нормування ---")
# Примітка: нормування перетворює дані так, щоб вони лежали в діапазоні від 0 до 1
df_normalized = (df[numeric_cols] - df[numeric_cols].min()) / (df[numeric_cols].max() - df[numeric_cols].min())
display(df_normalized.head())

print("\n--- Стандартизація ---")
# Примітка: стандартизація перетворює дані так, щоб середнє значення дорівнювало 0, а стандартне відхилення - 1
df_standardized = (df[numeric_cols] - df[numeric_cols].mean()) / df[numeric_cols].std()
display(df_standardized.head())

--- Нормування ---

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.374796,0.300719,0.376090,0.377593,0.0,0.0125,0.548387
1,0.478363,0.313669,0.336995,0.473029,0.0,0.0125,0.516129
2,0.479631,0.358273,0.326010,0.473029,0.0,0.0250,0.548387
3,0.480898,0.361151,0.340549,0.473029,0.0,0.0125,0.548387
4,0.325005,0.379856,0.403231,0.323651,0.0,0.0125,0.548387

--- Стандартизація ---

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2.955076,2.610720,-1.851816,3.098788,-0.182337,-0.051274,1.249420
1,4.037084,2.770405,-2.225274,4.133799,-0.182337,-0.051274,1.130897
2,4.050325,3.320431,-2.330213,4.133799,-0.182337,0.120487,1.249420
3,4.063566,3.355916,-2.191323,4.133799,-0.182337,-0.051274,1.249420
4,2.434881,3.586572,-1.592555,2.513781,-0.182337,-0.051274,1.249420

### 5: Кореляція Пірсона та Спірмена

Завдання: Підрахувати коефіцієнт Пірсона та Спірмена для двох integer/real атрибутів.

Для цього завдання я візьму атрибути Global_active_power та Global_intensity, оскільки з курсу фізики відомо, що вони мають бути сильно пов'язані.

In [11]:
# Рахуємо кореляцію між двома числовими атрибутами
col1 = 'Global_active_power'
col2 = 'Global_intensity'

# Коефіцієнт Пірсона (примітка: він оцінює лінійну залежність)
pearson_corr = df[col1].corr(df[col2], method='pearson')

# Коефіцієнт Спірмена (примітка: він оцінює монотонну залежність)
spearman_corr = df[col1].corr(df[col2], method='spearman')

print(f"--- Аналіз кореляції між '{col1}' та '{col2}' ---")
print(f"Коефіцієнт Пірсона:  {pearson_corr:.5f}")
print(f"Коефіцієнт Спірмена: {spearman_corr:.5f}")

--- Аналіз кореляції між 'Global_active_power' та 'Global_intensity' ---
Коефіцієнт Пірсона:  0.99889
Коефіцієнт Спірмена: 0.99537

### 6: One Hot Encoding

Завдання: Провести One Hot Encoding категоріального атрибута.

In [12]:
print("--- Проведення One Hot Encoding ---")

# Створюємо новий категоріальний атрибут "День тижня" з колонки Datetime
df['Day_of_Week'] = df['Datetime'].dt.day_name()
print("Створено категоріальну колонку 'Day_of_Week'. Початкові значення:")
display(df[['Datetime', 'Day_of_Week']].head())

# Застосовуємо One Hot Encoding (відповідна функція get_dummies в pandas)
# Ця функція створить окремі колонки для кожного дня зі значеннями True або False 
df_encoded = pd.get_dummies(df, columns=['Day_of_Week'], prefix='Day')

# Виводимо результат, щоб показати нові створені колонки
encoded_cols = [col for col in df_encoded.columns if col.startswith('Day_')]

print("\nРезультат One Hot Encoding (нові колонки):")
display(df_encoded[encoded_cols].head())

--- Проведення One Hot Encoding ---
Створено категоріальну колонку 'Day_of_Week'. Початкові значення:

             Datetime Day_of_Week
0 2006-12-16 17:24:00    Saturday
1 2006-12-16 17:25:00    Saturday
2 2006-12-16 17:26:00    Saturday
3 2006-12-16 17:27:00    Saturday
4 2006-12-16 17:28:00    Saturday

Результат One Hot Encoding (нові колонки):

,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,False,False,True,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,True,False,False,False,False
3,False,False,True,False,False,False,False
4,False,False,True,False,False,False,False